### ISSUE TITLE
用的新浪图床可能活不久

### ISSUE THREAD

**Issue by AHBICJ** [LampScript/qdaily_readme#2]
- 以最深的恶意揣测新浪的话，这图床得挂
- 以文字形式只抓取 标题+部分内容
- 抓取图片使用本地路径

**Comment by LampScript** [comment]
是的，新浪绝非长久之计，选新浪也只是出于性价比考虑，我会研究下国外的图床。
图片保存也不是一个完美的办法，只能说照顾好了点观看体验，仍然还是有很多信息的丢失。
谢谢你的建议 😊

**Comment by itning** [comment]
问一下 图片放在Github上会怎么样？

**Comment by LampScript** [comment]
> 问一下 图片放在Github上会怎么样？

能当图床用，但是国内速度慢

**Comment by LampScript** [comment]
已经备份到 https://web.archive.org
