### ISSUE TITLE
已备份到 gitee，还有为什么不保存文字

### ISSUE THREAD

**Issue by wizardforcel** [LampScript/qdaily_readme#5]
https://gitee.com/it-ebooks/qdaily-backup

**Comment by LampScript** [comment]
做得比较快，没意识保存文本的重要性，也没想到会有这么多人关注。
接下来会加上的。

**Comment by LampScript** [comment]
做得比较快，没意识保存文本的重要性，也没想到会有这么多人关注。
接下来会加上的。

**Comment by zoenglinghou** [comment]
@LampScript 我觉得 Zotero 和 SingleFileZ 保存网页效果都很好，考虑一下？

**Comment by wizardforcel** [comment]
算了 我自己爬吧
