### ISSUE TITLE
建议使用文档类型的存档格式

### ISSUE THREAD

**Issue by gonejack** [LampScript/qdaily_readme#7]
可以考虑 Chrome 的 mhtml 格式或者 Safari 的Webarchive 格式，两者都是为了保存网页而存在的，适合搜索和还原阅读效果。

或者 Chrome 插件 https://github.com/gildas-lormeau/SingleFileZ 可以存档为自带压缩内容（包含图片）的 html 文件，也是不错的通用解决方案。

**Comment by LampScript** [comment]
学习了！非常有用的帮助！

**Comment by LampScript** [comment]
已备份至 https://web.archive.org
